name: Build Web App

on:
  ## This tries to avoid unessesary pushes to forked repo
  ## development branches. No sense in a dev building every
  ## time they push for a PR and no one should be working on
  ## common branches in their fork.
  push:
    branches:
      - master
      - develop
      - 'hotfix/**'
      - 'release/**'
      - 'feature/**'
  pull_request:

jobs:
  test_build_release:

    name: Test, Build, and Publish
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      name: Checkout Code

    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet Packages
      run: nuget restore legacy-services.sln

    - name: Build
      run: |
        REM This will need to change when we add unit tests.
        msbuild LegacyCDE.Web\LegacyCDE.Web.csproj /p:TreatWarningsAsErrors=true /p:Configuration=Release
      shell: cmd

    # TODO: We need some unit tests.
    # - name: Run Unit Tests
    #   run: msbuild test\RunUnitTests.targets /p:Configuration=Release

    - name: Publish
      run: |
        msbuild legacy-services.sln /p:TreatWarningsAsErrors=true /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
        copy tools\deploy-site.ps1 publish\*.*
      shell: cmd

    - name: Record metadata
      uses: nciocpl/build-info-action@v1.0.0
      with:
        output-name: ${{ github.workspace }}/publish/dynamic-services/build-info.json

    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: dynamic-services
        path: .\publish
